version: '2'
services:
  blog:
    image: derchef/ghost:latest
    ports:
    - "2368:2368"
    - "2369:2369"
    environment:
    - url=http://localhost/pref
    volumes:
    - ghost-content:/var/lib/ghost/content

volumes:
  ghost-content:
