version: '3'
services:

  pref_blog:
    image: derchef/ghost:latest
    restart: always
    container_name: pref_blog
    ports:
      - "2368:2368"
    depends_on:
      - db
    environment:
      url: "$PREF_URL"
      database__client: mysql
      database__connection__host: pref_db
      database__connection__user: root
      database__connection__password: "$MYSQL_PASSWORD"
      database__connection__database: ghost
    volumes:
      - ./content:/var/lib/ghost/content
      - ./home:/home

  pref_ssh:
    image: derchef/ghost:latest
    container_name: pref_ssh
    depends_on:
      - pref_blog
    ports:
      - "2369:22"
    command: /usr/sbin/sshd -D
    volumes_from:
      - pref_blog

  pref_db:
    image: mysql:8.0
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_PASSWORD"
    
volumes:
  db:
