version: '2'
services:
  blog:
    build: .
    image: pref_ghost
    container_name: pref_ghost
    ports:
    - "2368:2368"
    environment:
    - url=http://localhost
    volumes:
    - ghost:/var/lib/ghost/
    - home:/home

  ssh:
    image: pref_ghost
    container_name: pref_ssh
    ports:
    - "2369:22"
    command: /usr/sbin/sshd -D
    volumes:
    - ghost:/var/lib/ghost
    - home:/home

volumes:
  ghost:
  home:
