version: '2'
services:
  blog:
    image: derchef/ghost:latest
    ports:
    - "80:2368"
    environment:
    - url=http://localhost
    volumes:
    - ghost-content:/var/lib/ghost/content

volumes:
  ghost-content:
